### ISSUE TITLE
Fix Openfire 4.9.0 compatibility

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-mucrtbl-plugin#23]
In [Openfire 4.9.0, deprecated API is being removed](https://igniterealtime.atlassian.net/browse/OF-2867) that is being used by this plugin. The deprecated API usage should be replaced, so that this plugin remains compatible with 4.9.0.

```
2024.08.23 06:56:07 ERROR [PluginMonitorExec-2]: org.jivesoftware.openfire.container.PluginManager - An exception occurred while loading plugin 'mucrtbl':
java.lang.NoSuchMethodError: 'void org.jivesoftware.util.TaskEngine.schedule(java.util.TimerTask, long, long)'
        at org.igniterealtime.openfire.plugin.mucrtbl.MucRealTimeBlockListPlugin.initializePlugin(MucRealTimeBlockListPlugin.java:147) ~[mucrtbl-1.1.0.jar:?]
        at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:640) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:380) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:368) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by guusdk** [comment]
A second compatibility issue:

```
2024.08.23 13:12:08 WARN [socket_s2s-thread-9]: org.igniterealtime.openfire.plugin.mucrtbl.BlockList - After adding entries to the block list, an event listener threw the following.
java.lang.NoSuchMethodError: 'java.util.Map org.jivesoftware.openfire.muc.spi.OccupantManager.getNodesByOccupant()'
    at org.igniterealtime.openfire.plugin.mucrtbl.OccupantRemover.added(OccupantRemover.java:65) ~[mucrtbl-1.1.1-SNAPSHOT.jar:?]
    at org.igniterealtime.openfire.plugin.mucrtbl.BlockList.addAll(BlockList.java:143) [mucrtbl-1.1.1-SNAPSHOT.jar:?]
    at org.igniterealtime.openfire.plugin.mucrtbl.PubSubHandler.handleIQResult(PubSubHandler.java:204) [mucrtbl-1.1.1-SNAPSHOT.jar:?]
    at org.igniterealtime.openfire.plugin.mucrtbl.PubSubHandler.interceptPacket(PubSubHandler.java:96) [mucrtbl-1.1.1-SNAPSHOT.jar:?]
    at org.jivesoftware.openfire.interceptor.InterceptorManager.invokeInterceptors(InterceptorManager.java:268) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
    at org.jivesoftware.openfire.interceptor.InterceptorManager.invokeInterceptors(InterceptorManager.java:230) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
    at org.jivesoftware.openfire.IQRouter.route(IQRouter.java:99) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
    at org.jivesoftware.openfire.spi.PacketRouterImpl.route(PacketRouterImpl.java:74) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
    at org.jivesoftware.openfire.net.StanzaHandler.processIQ(StanzaHandler.java:392) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
    at org.jivesoftware.openfire.net.ServerStanzaHandler.processIQ(ServerStanzaHandler.java:188) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
    at org.jivesoftware.openfire.net.StanzaHandler.process(StanzaHandler.java:334) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
    at org.jivesoftware.openfire.net.StanzaHandler.processStanza(StanzaHandler.java:222) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
    at org.jivesoftware.openfire.net.StanzaHandler.process(StanzaHandler.java:114) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
    at org.jivesoftware.openfire.nio.NettyConnectionHandler.channelRead0(NettyConnectionHandler.java:142) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
    at org.jivesoftware.openfire.nio.NettyConnectionHandler.channelRead0(NettyConnectionHandler.java:50) [xmppserver-4.9.0-SNAPSHOT.jar:4.9.0-SNAPSHOT]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [netty-codec-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [netty-codec-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:506) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530) [netty-codec-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469) [netty-codec-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [netty-codec-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.108.Final.jar:4.1.108.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.108.Final.jar:4.1.108.Final]
    at java.lang.Thread.run(Thread.java:829) [?:?] 
```
